use serde::{Deserialize, Serialize};

/// Direction of a frame relative to the daemon.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum Direction {
    Rx,
    Tx,
}

/// A CAN/CAN-FD frame event flowing through the daemon.
///
/// Right now, this is generated by a fake generator.
/// later it will come from SocketCAN RX and TX acknowledgements.
#[derive(Debug, Clone)]
pub struct FrameEvent {
    /// Unix timestamp in milliseconds.
    pub ts_ms: u64,

    /// Interface name (e.g., "can0", "vcan0").
    pub iface: String,

    /// Rx or Tx.
    pub dir: Direction,

    /// Raw arbitration id (11-bit or 29-bit). Representation details later.
    pub id: u32,

    /// True if CAN-FD, false if Classic CAN.
    pub is_fd: bool,

    /// Payload bytes. For Classic CAN: 0..=8, CAN-FD: 0..=64.
    pub data: Vec<u8>,
}
